### ISSUE TITLE
How to use with kinetic

### ISSUE THREAD

**Issue by orangetcy** [nobleo/full_coverage_path_planner#1]
Your project is so cool.  I found your project not standard ROS project tree, I can not follow your readme to get the result(I am a begainner for ros and slam). Could you please tech me more detail?

**Comment by orangetcy** [comment]
I got it: 
roslaunch full_coverage_path_planner test_full_coverage_path_planner.launch mismatch, should be:
roslaunch full_coverage_path_planner test_full_coverage_path_planner.test

**Comment by orangetcy** [comment]
Could you provide a test_full_coverage_path_planner.launch? I found I cannot use custom maps use with *.test launch file

**Comment by Timple** [comment]
We'll look into it!

**Comment by cesar-lopez-mar** [comment]
I have created a PR. You can use this branch in the mean time:

https://github.com/nobleo/full_coverage_path_planner/tree/fix/documentation
