### ISSUE TITLE
Running on Noetic

### ISSUE THREAD

**Issue by ehvenimunis** [nobleo/full_coverage_path_planner#11]
I got it working on noetic but when I run
roslaunch full_coverage_path_planner test_full_coverage_path_planner.launch
I get the following error 
![Screenshot from 2021-02-08 13-51-23](https://user-images.githubusercontent.com/43637760/107210166-d3309a00-6a14-11eb-8418-9b9be9ce536a.png)
![Screenshot from 2021-02-08 13-52-21](https://user-images.githubusercontent.com/43637760/107210214-e2174c80-6a14-11eb-9f99-d5137ae4ebd7.png)

**Comment by Timple** [comment]
The rviz screenshots are helpful. But would you mind removing the terminal part and pasting it in code-blocks? This allows users later to find your issue using the search.

**Comment by ethanckim** [comment]
I don't know if this thread is active, but from my experience trying to run the package on ROS Noetic, In order to fix the missing transform issue, you have to go to the `test_full_coverage_path_planner.launch` file and change the map_server node's frame id from [/map] to [map]:
```
    <node name="grid_server" pkg="map_server" type="map_server" args="$(arg map)">
        <param name="frame_id" value="map"/>
    </node>
```

**Comment by Timple** [comment]
`frame_id`s should not have (prepending) slashes.

Stripped them in #17

**Comment by ethanckim** [comment]
Thank you for the quick responce!
