### ISSUE TITLE
Can this be used as a plugin for standard move_base?

### ISSUE THREAD

**Issue by ryleymcc** [nobleo/full_coverage_path_planner#12]
Implementing move_base_flex would take some time so I'm wondering if I could just use this as a plugin for standard move_base.

**Comment by Timple** [comment]
The type is just a ["nav_core::BaseGlobalPlanner"](https://github.com/nobleo/full_coverage_path_planner/blob/master/fcpp_plugin.xml#L2). So yes, that should work.

**Comment by ryleymcc** [comment]
Thanks, ill try it out on my robotic lawnmower when I can.I'll be comparing it to my pre-recorded path plugin

**Comment by Timple** [comment]
Did you get this to work?

**Comment by ryleymcc** [comment]
> Did you get this to work?

I did not attempt.

**Comment by Timple** [comment]
Alright, closing then since it should work.

**Comment by 1234564lll** [comment]
如何

**Comment by 1234564lll** [comment]
> > Did you get this to work?
> 
> I did not attempt.

can it work
