### ISSUE TITLE
Altering waypoints

### ISSUE THREAD

**Issue by Ytodi31** [nobleo/full_coverage_path_planner#14]
Is it possible to alter the number of waypoints or set a maximum distance between two waypoints?

**Comment by Timple** [comment]
The number of waypoints comes from the algorithm. Of course we can describe a straight line with more points, but why would that be beneficial?

**Comment by Ytodi31** [comment]
So when dealing with obstacles, it skips the waypoints as intended but at the cost of large areas not being covered - with more waypoints I am hoping I can achieve better coverage
Any tips where I should look into for adding more points?

**Comment by Timple** [comment]
That sounds like it's a local-planner issue. So the planner should try to stick to the global plan as good as possible. I don't think it's the responsibility of this global planner to cover that?
