### ISSUE TITLE
Full coverage planner with kinematics

### ISSUE THREAD

**Issue by Wimll** [nobleo/full_coverage_path_planner#15]
Hi there!

I came across this package while looking for a coverage planner for my robot. However, the robot I am using is **not** a omnidirectional one and uses Ackermann steering like kinematics. This robot is not able to turn in place and driving backwards is also hard. Is there an option for this package to include the dynamics of the robot you're using? For example, by combining this package with the SBPL planner http://wiki.ros.org/sbpl_lattice_planner?

Thanks!

**Comment by Timple** [comment]
No, unfortunately not yet in this planner..

**Comment by Wimlpje** [comment]
Thanks for the heads-up Timpie!

**Comment by Timple** [comment]
:smile: Is that how my name is read?

**Comment by Wimlpje** [comment]
Excuse me, I misread your name for Timpie while it's actually Timple

**Comment by Timple** [comment]
I only now realize that you might not be the only one :wink:
