### ISSUE TITLE
Support for in-one-direction path pattern

### ISSUE THREAD

**Issue by saeedarabi92** [nobleo/full_coverage_path_planner#23]
Hi, Thanks for this great project!
I am experimenting with the full coverage path planning and (as it is obvious from the name of algorithm) it always create a _spiral_ pattern path like the following image.
![spiral](https://user-images.githubusercontent.com/25854555/126563702-cabca337-01ac-4e3f-91f1-8fc225df7255.png)
I was wondering if there is (or will be) any support for generating in-one-direction straight path pattern?
Thank you!

**Comment by cesar-lopez-mar** [comment]
Hello,

That depends on the needs of the application. When one of our projects requires this feature, we will include it. At this moment there are no plans to do so.
