### ISSUE TITLE
How to get the coverage plan for a particular polygonal area on the global map, instead of the whole global map.

### ISSUE THREAD

**Issue by amyjohansson1994** [nobleo/full_coverage_path_planner#5]
What params to specify so as to get coverage of only some particular zone on the map. 

Thank you

**Comment by Timple** [comment]
Unfortunately there is no such feature yet. Hence the **full_** in the name :wink: 
One option would be to enclose this area in the costmap so that the robot has no way out. In that case it should stay within the bounds.

**Comment by amyjohansson1994** [comment]
@Timple Thanks for the help. 

Trying to interpret your suggestion, I Understand that I need to have a script/package which will enclose the particular zone on the map from /map topic and publish it on another costmap2d topic. Then I need to specify this costmap2d topic to the full_coverage_path_planner package. 

I would really appreciate if you can correct me or point me to a resource where I can try figure it out myself.

**Comment by Timple** [comment]
I meant enclosing a room in your costmap. Something like this but then with the 'door' closed: 

![image](https://user-images.githubusercontent.com/5036851/96254744-14a8bf80-0fb6-11eb-855e-6a3081cf0184.png)

If the robot cannot leave the room, the coverage path will stay within that room.

**Comment by amyjohansson1994** [comment]
hi @Timple 

I tried your recommendation. It worked great for most part, but there was one anomaly I couldn't understand. 

As seen the picture below, the global path is not always same distance from the border (see the red arrows). 

Thank you so much for your responses

**Comment by Timple** [comment]
In the current implementation the complete area is divided into a grid. The above artifacts are an unfortunate result of that.

A better implementation would be a finer grained grid where multiple rows are covered so these edge-cases would be taken into account.
Unfortunately that is not there yet..
