### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by 1234564lll** [nobleo/full_coverage_path_planner#52]
Hello, I would like to know if it can be integrated into Movebase as a plugin

**Comment by Timple** [comment]
Yes it can, it identifies as a `nav_core::BaseGlobalPlanner`
https://github.com/nobleo/full_coverage_path_planner/blob/master/fcpp_plugin.xml

**Comment by 1234564lll** [comment]
> Yes it can, it identifies as a `nav_core::BaseGlobalPlanner` https://github.com/nobleo/full_coverage_path_planner/blob/master/fcpp_plugin.xml
Is his call in movebase similar to that of the teb plug-in
