### ISSUE TITLE
the topic msg of /cmd_vel is all wrong

### ISSUE THREAD

**Issue by realHarvey** [nobleo/full_coverage_path_planner#55]
at start, i need just rotate 90 degrees counterclockwise, but /cmd_vel message have a non-zero linear.x, might be such number like -10 or 6 ...
![a](https://github.com/nobleo/full_coverage_path_planner/assets/78713753/b55d30f1-be9d-4b7f-9e8e-b43a11657233)
i change the config " l " from defaut 0.5 to 0.001, then linear.x close to 0
BUT angular.z(the yaw) stays too long, my robot turns far more than 90 degs

**Comment by Timple** [comment]
This library outputs a path. It's not responsible for the /cmd_vel topic.

Although the launchfiles do include a full working example including the controller.
Is the odometry of your robot correct?

**Comment by realHarvey** [comment]
The /odom data is dead accurate. I didn't run into any snags with the odometry data when working on global motion planning.

you're right, maybe I should issue in "tracking_pid"
