### ISSUE TITLE
Can I use this package for my Turlebot3 burger Melodic version..

### ISSUE THREAD

**Issue by PVijayaGanesh** [nobleo/full_coverage_path_planner#56]
while launching the file i am facing this issues..

![ned2](https://github.com/user-attachments/assets/2c683d1c-e028-4edb-89f5-e4fcaf08a499)
![gt](https://github.com/user-attachments/assets/15cf504e-bad3-482f-9a3a-d37805ae4e3f)

@Timple @rokusottervanger @MCFurry @cesar-lopez-mar 
Please anyone help me with these...

**Comment by Timple** [comment]
Would you mind posting the terminal output in code brackets? That way it remains searchable.

As the warning states: `No controllers plugins configured`. So please configure a controller to do the local navigation for you.

**Comment by PVijayaGanesh** [comment]
How can i  configure a controller sir..
I am new to the ros..

please help me. Where i need to modify.. Please give me some roadmap i will try to do it. please sir..

**Comment by Timple** [comment]
If you are unfamiliar with ROS, I'd recommend not to use ROS 1 (which your are trying now). 

I'd get setup with the new navigation stack from ROS 2 and start from there: https://docs.nav2.org/

**Comment by PVijayaGanesh** [comment]
I am using FCPP on real turtlebot3 burger model...
But its not following the path what might be the reason i am not getting. I don't have time to start from scratch. @Timple 

Here i am pacing few things which might helpful to you to guide. Can you please help me sir..


`arm@arm:~/catkin_workspace$ roslaunch full_coverage_path_planner test_full_coverage_path_planner.launch
... logging to /home/arm/.ros/log/bdbe7c10-59f7-11ef-83d7-b8aeed34d29d/roslaunch-arm-13720.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://10.155.1.151:39657/

SUMMARY
========

PARAMETERS
 * /controller/Kd_lat: 0.3
 * /controller/Kd_long: 0.5
 * /controller/Ki_lat: 0.0
 * /controller/Ki_long: 0.0
 * /controller/Kp_lat: 4.0
 * /controller/Kp_long: 2.0
 * /controller/controller_debug_enabled: True
 * /controller/l: 0.5
 * /controller/track_base_link: True
 * /coverage_progress/coverage_radius: 0.3
 * /coverage_progress/map_frame: coverage_map
 * /coverage_progress/target_area/x: 10
 * /coverage_progress/target_area/y: 10
 * /grid_server/frame_id: map
 * /interpolator/target_x_vel: 0.5
 * /interpolator/target_yaw_vel: 0.4
 * /mobile_robot_simulator/odometry_topic: /odom
 * /mobile_robot_simulator/publish_map_transform: True
 * /mobile_robot_simulator/publish_rate: 10.0
 * /mobile_robot_simulator/velocity_topic: /move_base/cmd_vel
 * /move_base/base_global_planner: SpiralSTC
 * /move_base_flex/SpiralSTC/robot_radius: 0.3
 * /move_base_flex/SpiralSTC/tool_radius: 0.3
 * /move_base_flex/global_costmap/cost_scaling_factor: 3.0
 * /move_base_flex/global_costmap/footprint: [[-0.105, -0.105]...
 * /move_base_flex/global_costmap/inflation_radius: 1.0
 * /move_base_flex/global_costmap/map_type: costmap
 * /move_base_flex/global_costmap/observation_sources: scan
 * /move_base_flex/global_costmap/obstacle_range: 3.0
 * /move_base_flex/global_costmap/raytrace_range: 3.5
 * /move_base_flex/global_costmap/robot_radius: 0.3
 * /move_base_flex/global_costmap/scan/clearing: True
 * /move_base_flex/global_costmap/scan/data_type: LaserScan
 * /move_base_flex/global_costmap/scan/marking: True
 * /move_base_flex/global_costmap/scan/sensor_frame: base_scan
 * /move_base_flex/global_costmap/scan/topic: scan
 * /move_base_flex/local_costmap/cost_scaling_factor: 3.0
 * /move_base_flex/local_costmap/footprint: [[-0.105, -0.105]...
 * /move_base_flex/local_costmap/global_frame: odom
 * /move_base_flex/local_costmap/height: 5.0
 * /move_base_flex/local_costmap/inflation_radius: 1.0
 * /move_base_flex/local_costmap/map_type: costmap
 * /move_base_flex/local_costmap/observation_sources: scan
 * /move_base_flex/local_costmap/obstacle_range: 3.0
 * /move_base_flex/local_costmap/publish_frequency: 5.0
 * /move_base_flex/local_costmap/raytrace_range: 3.5
 * /move_base_flex/local_costmap/resolution: 0.05
 * /move_base_flex/local_costmap/robot_base_frame: base_link
 * /move_base_flex/local_costmap/rolling_window: True
 * /move_base_flex/local_costmap/scan/clearing: True
 * /move_base_flex/local_costmap/scan/data_type: LaserScan
 * /move_base_flex/local_costmap/scan/marking: True
 * /move_base_flex/local_costmap/scan/sensor_frame: base_scan
 * /move_base_flex/local_costmap/scan/topic: scan
 * /move_base_flex/local_costmap/static_map: False
 * /move_base_flex/local_costmap/update_frequency: 10.0
 * /move_base_flex/local_costmap/width: 5.0
 * /move_base_flex/planners: [{'name': 'Spiral...
 * /move_base_flex/tf_timeout: 1.5
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /
    controller (tracking_pid/controller)
    coverage_progress (full_coverage_path_planner/coverage_progress)
    grid_server (map_server/map_server)
    interpolator (tracking_pid/path_interpolator)
    map_to_coveragemap (tf/static_transform_publisher)
    mobile_robot_simulator (mobile_robot_simulator/mobile_robot_simulator_node)
    move_base (mbf_costmap_nav/move_base_legacy_relay.py)
    move_base_flex (mbf_costmap_nav/mbf_costmap_nav)
    publish_simple_goal (rostopic/rostopic)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://10.155.1.151:11311

process[move_base_flex-1]: started with pid [13735]
process[move_base-2]: started with pid [13736]
process[mobile_robot_simulator-3]: started with pid [13737]
process[grid_server-4]: started with pid [13742]
process[interpolator-5]: started with pid [13749]
process[controller-6]: started with pid [13752]
process[map_to_coveragemap-7]: started with pid [13753]
process[coverage_progress-8]: started with pid [13761]
process[publish_simple_goal-9]: started with pid [13768]
process[rviz-10]: started with pid [13774]
[ INFO] [1723612253.564754487]: Initialized mobile robot simulator
[ INFO] [1723612253.566280946]: --- Starting MobileRobot simulator
[ INFO] [1723612253.588043850]: CONTROLLER PARAMETERS
[ INFO] [1723612253.589312141]: -----------------------------------------
[ INFO] [1723612253.589348282]: Controller enabled: 1
[ INFO] [1723612253.589363148]: Controller DEBUG enabled: 1
[ INFO] [1723612253.589381746]: Distance L: 0.500000
[ INFO] [1723612253.589396058]: Feedback (long, lat, ang): (1, 1, 1)
[ INFO] [1723612253.589409502]: Feedforward (long, lat, ang): (1, 1, 0)
[ INFO] [1723612253.589428836]: Longitudinal gains: (Kp: 2.000000, Ki, 0.000000, Kd, 0.500000)
[ INFO] [1723612253.589449317]: Lateral gains: (Kp: 4.000000, Ki, 0.000000, Kd, 0.300000)
[ INFO] [1723612253.589469046]: Angular gains: (Kp: 1.000000, Ki, 0.000000, Kd, 0.300000)
[ INFO] [1723612253.589487031]: Robot type (holonomic): (0)
[ INFO] [1723612253.589504231]: Track base link: (1)
[ INFO] [1723612253.589522780]: LPF cutoff frequency: 1/4 of sampling rate
[ INFO] [1723612253.589543062]: Integral-windup limit: 1000.000000
[ INFO] [1723612253.589561489]: Saturation limits xy: 10.000000/-10.000000
[ INFO] [1723612253.589580442]: Saturation limits ang: 10.000000/-10.000000
[ INFO] [1723612253.589598711]: map frame: 
[ INFO] [1723612253.589616225]: base_link frame: 
[ INFO] [1723612253.589633480]: -----------------------------------------
[ INFO] [1723612253.666549822]: Started mobile robot simulator update loop, listening on cmd_vel topic
[ WARN] [1723612253.875184122]: local_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1723612253.877745656]: local_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1723612253.878964623]: local_costmap: Using plugin "obstacle_layer"
[ INFO] [1723612253.889044316]:     Subscribed to Topics: 
[ INFO] [1723612253.900454529]: local_costmap: Using plugin "inflation_layer"
[ INFO] [1723612253.915851974]: Transform between map and base_link found
[ WARN] [1723612253.949792948]: global_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1723612253.950677112]: global_costmap: Using plugin "obstacle_layer"
[ INFO] [1723612253.957848186]:     Subscribed to Topics: 
[ INFO] [1723612253.973375854]: global_costmap: Using plugin "inflation_layer"
[ INFO] [1723612254.058563330]: The plugin with the type "full_coverage_path_planner/SpiralSTC" has been loaded successfully under the name "SpiralSTC".
[ INFO] [1723612254.067627383]: Sim period is set to 0.05
[ INFO] [1723612254.208430672]: The plugin with the type "dwa_local_planner/DWAPlannerROS" has been loaded successfully under the name "DWAPlannerROS".
[ WARN] [1723612254.209296766]: No recovery_behaviors plugins configured! - Use the param "recovery_behaviors", which must be a list of tuples with a name and a type.
[ INFO] [1723612254.318070685]: odom received!
[WARN] [1723612254.770425]: Lookup would require extrapolation at time 1723612254.766515255, but only time 1723612254.848130465 is in the buffer, when looking up transform from frame [base_link] to frame [coverage_map]
[ INFO] [1723612255.324011800]: Initialized!
[ INFO] [1723612255.326950762]: Requesting grid!!
[ INFO] [1723612255.329892513]: nRows: 152 nCols: 127 nodeSize: 12
[ INFO] [1723612255.330304059]: naive cpp completed!
[ INFO] [1723612255.330354224]: Converting path to plan
[ INFO] [1723612255.330415058]: Received goalpoints with length: 155
[ INFO] [1723612255.330552372]: Plan ready containing 130 goals!
[ INFO] [1723612255.330593984]: Total visited: 143
[ INFO] [1723612255.330629505]: Total re-visited: 48
[ INFO] [1723612255.330661924]: Total accessible cells: 95
[ INFO] [1723612255.330709281]: Total accessible area: 34.200003
[ INFO] [1723612255.330743848]: Publishing plan!
[ INFO] [1723612255.330819293]: Plan published!
elapsed time: 0.002789
[ INFO] [1723612255.348870735]: Got new plan
[ WARN] [1723612257.897754603]: DWA planner failed to produce path.
[ WARN] [1723612257.897941194]: No velocity command received from controller! Controller failed
[ WARN] [1723612257.947096242]: DWA planner failed to produce path.
[ WARN] [1723612257.998467137]: DWA planner failed to produce path.
[ WARN] [1723612258.197435871]: DWA planner failed to produce path.
[ WARN] [1723612258.297242077]: DWA planner failed to produce path.
[ WARN] [1723612258.396701035]: DWA planner failed to produce path.
[ WARN] [1723612258.897014036]: DWA planner failed to produce path.
[ WARN] [1723612259.097264491]: DWA planner failed to produce path.
[ WARN] [1723612259.147049920]: DWA planner failed to produce path.
[ WARN] [1723612259.546506959]: DWA planner failed to produce path.
[ WARN] [1723612259.596995260]: DWA planner failed to produce path.
[ WARN] [1723612259.646714589]: DWA planner failed to produce path.
[ WARN] [1723612259.747013248]: DWA planner failed to produce path.
[ WARN] [1723612259.796952939]: DWA planner failed to produce path.
[ WARN] [1723612267.596959205]: DWA planner failed to produce path.
[ WARN] [1723612267.597139223]: No velocity command received from controller! Controller failed
[ WARN] [1723612267.646911314]: DWA planner failed to produce path.
[ WARN] [1723612267.796600110]: DWA planner failed to produce path.
[ WARN] [1723612267.896604428]: DWA planner failed to produce path.
[ WARN] [1723612268.196608845]: DWA planner failed to produce path.
[ WARN] [1723612268.296715760]: DWA planner failed to produce path.
[ WARN] [1723612296.247588006]: DWA planner failed to produce path.
[ WARN] [1723612296.248112919]: No velocity command received from controller! Controller failed
[ WARN] [1723612296.346801127]: DWA planner failed to produce path.
[ WARN] [1723612296.396500930]: DWA planner failed to produce path.
[ WARN] [1723612296.446502773]: DWA planner failed to produce path.
[ WARN] [1723612297.397276126]: DWA planner failed to produce path.
[ WARN] [1723612297.596620097]: DWA planner failed to produce path.
[ WARN] [1723612297.797231801]: DWA planner failed to produce path.
[ WARN] [1723612303.297233836]: DWA planner failed to produce path.
[ WARN] [1723612303.297354514]: No velocity command received from controller! Controller failed
`


And here is my controller.yaml file

`controllers:
  - name: 'tracking_pid'
    type: 'tracking_pid/TrackingPidLocalPlanner'

  - name: DWAPlannerROS
    type: dwa_local_planner/DWAPlannerROS

controller:
  holonomic_robot: false

mbf_tolerance_check: true
dist_tolerance: 0.2
angle_tolerance: 0.5`



And my launch is like this..

`    
    <node pkg="mbf_costmap_nav" type="mbf_costmap_nav" respawn="false" name="move_base_flex" output="screen" required="true">
        <param name="tf_timeout" value="1.5"/>
        <rosparam file="$(find turtlebot3_navigation)/param/costmap_common_params_$(arg model).yaml" command="load" ns="global_costmap" />
        <rosparam file="$(find turtlebot3_navigation)/param/costmap_common_params_$(arg model).yaml" command="load" ns="local_costmap" />
        <rosparam file="$(find full_coverage_path_planner)/test/full_coverage_path_planner/param/planners.yaml" command="load" />
        <rosparam file="$(find full_coverage_path_planner)/test/full_coverage_path_planner/param/local_costmap_params.yaml" command="load" />
        <param name="SpiralSTC/robot_radius" value="$(arg robot_radius)"/>
        <param name="SpiralSTC/tool_radius" value="$(arg tool_radius)"/>
        <param name="global_costmap/robot_radius" value="$(arg robot_radius)"/>
        <remap from="odom" to="/odom"/>
        <remap from="scan" to="/scan"/>

        <remap from="/move_base_flex/SpiralSTC/plan" to="/move_base/SpiralSTC/plan"/>
        <remap from="/move_base_flex/tracking_pid/interpolator" to="/move_base/TrackingPidLocalPlanner/interpolator"/>
    </node>

    
    <node pkg="mbf_costmap_nav" type="move_base_legacy_relay.py" name="move_base" >
        <param name="base_global_planner" value="SpiralSTC" />
        
    </node>`
    
    
    
    Please help me...
@Timple

**Comment by PVijayaGanesh** [comment]
Thank you @nsk-05
