### ISSUE TITLE
Setting the Tool radius larger than the robot_radius leads to errors

### ISSUE THREAD

**Issue by gribes02** [nobleo/full_coverage_path_planner#58]
Hi,

I wanted to use a tool radius larger than the robot radius, in my case the robot cleans through the use of water jets and thus cleans quite a large area. I saw that if I set the tool radius larger than the robot radius it would cause the path to be incorrect setting paths that go thorough walls. Why is this the case? 

Example of the tool radius being smaller than the robot radius
![image](https://github.com/user-attachments/assets/bfc23e69-a35e-4ea6-a8df-24a03028338b)

Example of the tool radius being larger than the robot radius
![image](https://github.com/user-attachments/assets/44467fd4-6061-4a95-8220-a1626bd3aded)

Note this is only the case when the tool radius is significantly larger than the robot radius. In the example provided the tool radius was set to 0.18 and the robot radius to 0.15

**Comment by Timple** [comment]
Thanks for the detailed explanation. And apologies for the delay!

A toolsize larger than the robot has (obviously) not been an anticipated. Did you ever solve the issue? Any contributions in that direction would be welcome!

**Comment by gribes02** [comment]
Hello, sadly I have not pursued this package further and thus have not attempted a solution. Nonetheless, thanks for the reply :)
