### ISSUE TITLE
Running on Noetic

### ISSUE THREAD

**Issue by ElClopitan** [nobleo/full_coverage_path_planner#7]
I got it working on noetic but when I run 
roslaunch full_coverage_path_planner test_full_coverage_path_planner.launch
I get the following error from dynamic reconfigure
![Screenshot from 2020-10-29 15-48-37](https://user-images.githubusercontent.com/23469686/97640561-42eabe00-19fe-11eb-8cc3-0300f5674693.png)
and while the robot moves on the path, the transform from the robot to the map seems to be missing.
![Screenshot from 2020-10-29 15-43-47](https://user-images.githubusercontent.com/23469686/97640472-0ae37b00-19fe-11eb-8234-1b891c003a25.png)
Is this just an issue of publishing a transform myself and if so where can I get the transform info?

**Comment by amyjohansson1994** [comment]
@ElClopitan I had similar issue, and found the solution at magazino/move_base_flex#224

**Comment by ElClopitan** [comment]
I realized the problem of it dying was error on my part but upon fixing it, the original issue of the maps being misaligned remains. Any help is appreciated thank you!

**Comment by ElClopitan** [comment]
@amyjohansson1994 I followed your advice and replaced move_base_legacy_relay.py with the one from noetic-devel branch and did the other fix on there so it runs again. The original issue remains and I think I have narrowed it down to mobile_robot_simulator publishing the robot's base_link to be at (0,0) on the map which is not correct. Manually publishing a tf messes up the path so is there another way I can fix this? Thank you!

**Comment by Timple** [comment]
So mobile_robot_simulator is broken on Noetic?

**Comment by ElClopitan** [comment]
It seems to be running fine, just that it places the robot at (0,0) on the map. If that counts as broken then yeah, it's broken. Hopefully there is a fix. It may just be that there is no source for localization on this map.

**Comment by ElClopitan** [comment]
Even if I give it a correct initial position, the path does not move with it so it seems to start at the point closest to the new position.

**Comment by ElClopitan** [comment]
Looking at a kinetic version of the code that works, I think it is safe to say that mobile robot simulator is the issue. I'll close this for now but if someone has any potential solutions I would be grateful.

**Comment by Timple** [comment]
Feel free to open an issue on robot_mobile_simulator for this :)
