### ISSUE TITLE
Trying to get this package installed and running

### ISSUE THREAD

**Issue by ryleymcc** [nobleo/full_coverage_path_planner#8]
When I follow your install instructions and run the command
`sudo catkin build full_coverage_path_planner --catkin-make-args run_tests`
It says this
`The build space at '/home/ryley/catkin_ws/build' was previously built by 'catkin_make'. Please remove the build space or pick a different build space.
`
Please advise

**Comment by ryleymcc** [comment]
Deleted my build and devel directory and ran `catkin build` then ran `sudo catkin build full_coverage_path_planner --catkin-make-args run_tests` successfully with warnings.

**Comment by ryleymcc** [comment]
Issues when I run the command `roslaunch full_coverage_path_planner test_full_coverage_path_planner.launch` from the readme.

RVIS launches and the map does not load.
![Screenshot from 2020-12-10 03-36-16](https://user-images.githubusercontent.com/41346879/101754006-e23caf80-3a98-11eb-9661-2ef4df27bfa8.png)

going to try to manually point to the grid.yaml file without the (find pkg_name)/maps/grid.yaml but would like to know why its not finding it. Might be due to the previous issue.

**Comment by ryleymcc** [comment]
I'm going to guess and say that running make build has isolated this package from its dependencies. Not sure tho since I'm new to linux and ros and catkin

**Comment by ryleymcc** [comment]
I ran `sudo catkin clean -y` and catkin build and i got errors from this package.

`Starting  >>> full_coverage_path_planner                                                                       
_______________________________________________________________________________________________________________
Warnings   << full_coverage_path_planner:make /home/ryley/catkin_ws/logs/full_coverage_path_planner/build.make.000.log
/home/ryley/catkin_ws/src/full_coverage_path_planner/src/common.cpp: In function ‘bool a_star_to_open_space(const std::vector<std::vector<bool> >&, gridNode_t, int, std::vector<std::vector<bool> >&, const std::__cxx11::list<Point_t>&, std::__cxx11::list<gridNode_t>&)’:
/home/ryley/catkin_ws/src/full_coverage_path_planner/src/common.cpp:140:29: warning: narrowing conversion of ‘(((uint)nn.std::vector<gridNode_t>::back().gridNode_t::pos.Point_t::x) + dx)’ from ‘uint’ {aka ‘unsigned int’} to ‘int’ [-Wnarrowing]
  140 |             nn.back().pos.x + dx,
      |             ~~~~~~~~~~~~~~~~^~~~
/home/ryley/catkin_ws/src/full_coverage_path_planner/src/common.cpp:141:29: warning: narrowing conversion of ‘(((uint)nn.std::vector<gridNode_t>::back().gridNode_t::pos.Point_t::y) + dy)’ from ‘uint’ {aka ‘unsigned int’} to ‘int’ [-Wnarrowing]
  141 |             nn.back().pos.y + dy,
      |             ~~~~~~~~~~~~~~~~^~~~
/home/ryley/catkin_ws/src/full_coverage_path_planner/src/common.cpp:166:80: warning: narrowing conversion of ‘(((uint)((cost + nn.std::vector<gridNode_t>::back().gridNode_t::cost) + distanceToClosestPoint(p2, (* & open_space)))) + i)’ from ‘uint’ {aka ‘unsigned int’} to ‘int’ [-Wnarrowing]
  166 |                 cost + nn.back().cost + distanceToClosestPoint(p2, open_space) + i,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
cd /home/ryley/catkin_ws/build/full_coverage_path_planner; catkin build --get-env full_coverage_path_planner | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -
...............................................................................................................
Finished  <<< full_coverage_path_planner                [ 5.4 seconds ]                                        
[build] Summary: All 15 packages succeeded!                                                                    
[build]   Ignored:   None.                                                                                     
[build]   Warnings:  2 packages succeeded with warnings.                                                       
[build]   Abandoned: None.                                                                                     
[build]   Failed:    None.                                                                                     
[build] Runtime: 26.2 seconds total.                                                                           
[build] Note: Workspace packages have changed, please re-source setup files to use them.`

**Comment by amyjohansson1994** [comment]
@ryleymcc I might be late to this.

1. You do not have to build using `catkin build`, just do `catkin_make` without any arguments. 
2. I preferred having setup the move_base_flex  (whole of navstack actually) for my gazebo environment along with SLAM
 and then test the package.

**Comment by Timple** [comment]
A bug was fixed which resulted in the launchfile not working.

Assuming this works now :slightly_smiling_face:
